FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    avr-libc \
    gcc-avr \
    avrdude \
    make \
    cmake \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Set working dir
WORKDIR /workspace
